config/routes.rb
Rails.application.routes.draw do

  root 'items#index'

  resources :items
  resources :users
  resources :transactions

end

app/models/item.rb
class Item < ActiveRecord::Base
	belongs_to :user
	has_many :transactions
end

app/models/transaction.rb
class Transaction < ActiveRecord::Base
  belongs_to :user
  belongs_to :item
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :items
	has_many :transactions
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
	before_action :set_item, only: [:show, :edit, :update, :destroy]
	def index
		@items = Item.all.order('created_at DESC')
	end

	def new
		@item = Item.new
	end
	def show  
	end  

	def create
		if @item = Item.create(item_params)
			flash[:success] = "Your item has been created!"
			redirect_to items_path
		else
			flash.now[:alert] = "Your new item couldn't be created!  Please check the form."
			render :new
		end
	end
	def edit  
		@item = Item.find(params[:id])
	end

	def update
		old_user = @item.user  
		if @item.update(item_params)
		  puts "Hello World ---------- #{old_user}"
		  puts "Hello World ---------- #{item_params[:user_id]}"
		  create_transactions(@item,old_user)
	      flash[:success] = "Item updated."
	      redirect_to items_path
	    else
	      flash.now[:alert] = "Update failed.  Please check the form."
	      render :edit
	    end	

	end  
	def destroy  
	  @item.destroy
	  redirect_to items_path
	end 

	def create_transactions(item, old_user) 
		Transaction.create(user_id: old_user.id, item_id: item.id, transaction_type: 'removed', removed_on: Date.today) if old_user
		Transaction.create(user_id: item_params[:user_id], item_id: item.id, transaction_type: 'added', assigned_on: Date.today)
	end

	private

	def item_params
		params.require(:item).permit(:equipment_type,:model_number, :serial, :cost, :description,:purchase_date, :user_id)
	end

	def set_item
		@item = Item.find(params[:id])
	end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
	def index
		@transactions = Transaction.all.order('created_at DESC')
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :set_user, only: [:show, :edit,:update, :destroy]
	def index
		@users = User.all
	end
	def new
		@user = User.new
	end
	def show
		@transactions = Transaction.where(user_id: @user.id)
	end
	def edit

	end
	def create
		if @user = User.create(user_params)
			flash[:success] = "User created"
			redirect_to users_path
		else
			flash[:alert] = "User not created"
			redirect_to :new
		end
	end
	def update
		if @user.update(user_params)
			flash[:success] = "User information updated"
			redirect_to user_path(@user)
		else
			flash[:alert] = "Something went wrong while creating user"
			redirect_to :edit
		end
	end
	def detroy
		if @user.destroy
			redirect_to users_path
		else
			render :edit
		end
	end

	private
	def set_user
		@user = User.find(params[:id])
	end
	def user_params
		params.require(:user).permit(:name, :email,:company,:location)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def alert_for(flash_type)  
	  { success: 'alert-success',
	    error: 'alert-danger',
	    alert: 'alert-warning',
	    notice: 'alert-info'
	  }[flash_type.to_sym] || flash_type.to_s
end  
end

app/helpers/items_helper.rb
module ItemsHelper
	def get_user_name item
		return item.user.name if item.user
		return 'Inventory'
	end
end

app/helpers/transactions_helper.rb
module TransactionsHelper
	def transaction_info transaction, count
		if transaction.user != nil
			name = transaction.user.name
		else
			name = ''
		end
		"#{count+1}) #{transaction.item.serial} has been #{transaction.transaction_type} to/from #{name} on #{transaction.created_at}"
	end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/items/edit.html.haml
.text-center
  = @item.serial
.form-wrapper
  = simple_form_for @item, html: { class: 'form-horizontal', multipart: true } do |f|
    .form-group
      = f.input :equipment_type
    .form-group.text-center
      = f.input :model_number
    .form-group.text-center
      = f.input :serial
    .form-group.text-center
      = f.input :description
    .form-group.text-center
      = f.input :purchase_date
    .form-group.text-center
      = f.input :user_id, collection: User.all
    .form-group.text-center
      = f.button :submit, class: 'btn-success'
  .text-center.edit-links
  = link_to "Delete Item", item_path(@item), method: :delete, data: { confirm: "Are you sure you want to delete this item?" }
  |
  = link_to "cancel", items_path

app/views/items/index.html.haml
.item-wrapper
  - @items.each do |item|
    %h3 
      =item.equipment_type
      with S/N:
      = item.serial
    %div.row.item
      %div.col-xs-3.form-group
        %h5 <b> Type:</b>
        .reg_name
          = item.equipment_type
      %div.col-xs-3.form-group
        %h5 <b> Model:</b>
        .reg_name
          = item.model_number
      %div.col-xs-3.form-group
        %h5 <b> Serial Number:</b>
        .reg_name
          = item.serial
      %div.col-xs-3.form-group
        %h5 <b> Description:</b>
        .reg_name
          = item.description
      %div.col-xs-3.form-group
        %h5 <b> Cost($):</b>
        .reg_name
          = item.cost
      %div.col-xs-3.form-group
        %h5 <b> Purchase Date:</b>
        .reg_name
          = item.purchase_date
      %div.col-xs-3.form-group
        %h5 <b> Belongs to User:</b>
        .reg_name
          = get_user_name(item)
      %div.col-xs-3.form-group
        %br
        = link_to "Edit Item", edit_item_path(item)

app/views/items/new.html.haml
= simple_form_for @item , wrapper_mappings: { heck_boxes: :vertical_radio_and_checkboxes, radio_buttons: :vertical_radio_and_checkboxes, file: :vertical_file_input, boolean: :vertical_boolean }do |f|
  = f.input :equipment_type, placeholder: 'Type' 
  = f.input :model_number, placeholder: 'Model'
  = f.input :serial, placeholder: 'Serial Number'
  = f.input :cost, placeholder: 'Cost($)'
  = f.input :description, placeholder: 'Description'
  = f.input :purchase_date, placeholder: 'Purchase Date'
  = f.button :submit
  

app/views/items/show.html.haml
.posts-wrapper.row
  .item
    =@item.serial
    
    %p.caption
      =@item.description
    .text-center.edit-links
      = link_to "Cancel", items_path
      |
      = link_to "Edit Item", edit_item_path(@item)

app/views/layouts/_navigation.html.haml
%nav.navbar.navbar-default
  .navbar-container
    .navbar-header
      %button.navbar-toggle.collapsed{"data-target" => ".bs-navbar-collapse-1", "data-toggle" => "collapse", type: "button"}
        %span.sr-only Toggle Navigation
        %span.icon-bar
        %span.icon-bar
      .navbar-brand= link_to "Vision Inventory", root_path
    .collapse.navbar-collapse.bs-navbar-collapse-1
      %ul.nav.navbar-nav.navbar-right
        %li
          = link_to "New Item", new_item_path
        %li
          = link_to "New User", new_user_path
        %li
          = link_to "User list", users_path
        

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title Inventory App
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags

  %body
    = render 'layouts/navigation'
    .container.fill
      -flash.each do |name, msg|
        = content_tag :div, msg, class: [:alert, alert_for(name)]
      = yield

app/views/transactions/index.html.haml
.item-wrapper
  - @transactions.each_with_index do |transaction,count|
    %div.user.row
      = transaction_info(transaction,count)

app/views/users/edit.html.haml
.text-center
  = @user.serial
.form-wrapper
  = simple_form_for @user, html: { class: 'form-horizontal', multipart: true } do |f|
    .form-group
      = f.input :name
    .form-group.text-center
      = f.input :email
    .form-group.text-center
      = f.input :company
    .form-group.text-center
      = f.input :location
    .form-group.text-center
      = f.button :submit, class: 'btn-success'
  .text-center.edit-links
  = link_to "Delete User", user_path(@user), method: :delete, data: { confirm: "Are you sure you want to delete this user?" }
  |
  = link_to "cancel", users_path

app/views/users/index.html.haml
.item-wrapper
  - @users.each do |user|
    %div.user.row
      %div.caption.col-xs-6.col-lg-6
        Name:
        = user.name
      %div.caption.col-xs-6.col-lg-6
        Email:
        = user.email
      %div.caption.col-xs-6.col-lg-6
        Company:
        = user.company
      %div.caption.col-xs-6.col-lg-6
        Location:
        = user.location
      .text-center.edit-links
        = link_to "Edit user", edit_user_path(user)
        = link_to "User Profile", user_path(user)

app/views/users/new.html.haml
= simple_form_for @user do |f|
  = f.input :name, label: 'Name'
  = f.input :email, label: 'Email'
  = f.input :company, label: 'Company'
  = f.input :location, label: 'Location'
  = f.button :submit
  

app/views/users/show.html.haml
.items-wrapper.row
  %h2
    User Profile
  .item
    Name:
    =@user.name
    %br 
    Email:
    =@user.email
    %br 
    Company:
    =@user.company
    %br 
    Location:
    =@user.location
    
    
      
    .text-center.edit-links
      = link_to "Cancel", users_path
      |
      = link_to "Edit user", edit_user_path(@user)
.items-wrapper.row
  %h3
    User Inventory
  %br
  -@user.items.each_with_index do |item, count|
    %div.row.item
      = "#{count+1}) #{item.equipment_type}, model number #{item.model_number} with serial number #{item.serial}"
    

.items-wrapper.row
  %h3
    User Transactions
  %br
  -@transactions.each_with_index do |transaction, count|
    %div.row.item
      = "#{count +1}) #{transaction.item.serial} has been #{transaction.transaction_type} on #{transaction.created_at}"
    